### ISSUE TITLE
Standardize how PL family of blogs are published

### ISSUE THREAD

**Issue by mishmosh** [ipfs/blog#105]
Per @diasdavid suggestion, we should standardize how we publish blog posts across properties -- Digital Ocean, etc.

**Comment by diasdavid** [comment]
blogs + websites. Ideally, everything should be automated.

**Comment by lgierth** [comment]
The standards are: Hugo for the static site generator, and DNSimple API for the dnslink update.

The reason we're still dealing with metalsmith (blog) and pelican (website) is that nobody has successfully converted them to Hugo yet. I have in-progress branches for this which I'll be most happy to intro to someone :)

The reason Digitalocean is still part of the deploy for a few sites, is that we haven't moved the ipfs.io domain to DNSimple yet. It's on my todo list, just haven't found a good moment yet.

**Comment by lgierth** [comment]
Oh and I also have a bit of in-progress code for automating the build and deploy of website based on PRs and merges.
