### ISSUE TITLE
Blog Post: Introducing IPLD

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#106]
We haven't yet published any article explaining IPLD -- there's just the spec, the website, and the working code. We should publish a post that introduced IPLD, explains the motivation, explains the possibilities, explains the main concepts, and points to where we're using it.

**Comment by VictorBjelkholm** [comment]
Don't get me wrong, a blogpost about IPLD would be great, but if the
website doesn't "introduce IPLD, explains the motivation, explains the
possibilities, explains the main concepts, and points to where we're using
it", we need to extend the website to do this, rather than writing a
blog-post. Many peoples first point of entry will be the website, and
unless we can convey this information effectively, they are not gonna
navigate to a article about IPLD.

**Comment by flyingzumwalt** [comment]
I'm not saying that the website is missing info. I'm proposing that we write a blog post and I'm outlining what should be in that post. We need both the blog post and the website to provide all of that information. I imagine the blog post will have a mix of narrative tone ("we found that we needed...) and descriptive examples ("imagine you have data like..."). This might end up presenting the same exact information and examples that the website presents, but it will provide the info in a different way. 

In addition to reaching new audiences who might not know about the IPLD website yet, this will also be one more post to keep the blog's pulse regular.

**Comment by jesseclay** [comment]
@flyingzumwalt @VictorBjelkholm I think it's a great idea to to release a blog post on this, and preferably we could do it this week. Is the IPFS blog the best place for this or the protocol.ai blog? Or maybe we can do both?

Would love to see this a post launch this week.

**Comment by flyingzumwalt** [comment]
I wasn't planning to write about IPLD this week. We have a lot of other things to write and publish this week. This issue is just registering the idea in the blog pipeline.

This post belongs on the ipfs blog.

**Comment by mishmosh** [comment]
Great idea and timely. Let's figure out the path to make this happen.

@flyingzumwalt I'm booking 30 mins with you, and I will attempt to write based on our conversation. Feel free to reschedule if you are short on time this week.

**Comment by flyingzumwalt** [comment]
Sounds good. FYI - I think it will be better to focus on the IIIF on IPRS demos first, before publishing the IPLD post, especially since the IIIF demos include code examples and a strong narrative — high res images on the decentralized web, annotations, virtual reality, the Vatican.

ནོར་ཞིང་ནོར་ཞིང་ཡང་དག་ལམ་ལ་འཇུག།
“mistake by mistake, I walk the unmistaken path”

**Comment by mishmosh** [comment]
I think we can multi-thread this, with you owning the IIIF post and me the
IPLD one.

**Comment by flyingzumwalt** [comment]
Make sure to loop Henri into this too (don't know his github handle) -- he dealt with the giant task of gathering all the scattered info about IPLD and getting it refined into consumable form on https://ipld.io

**Comment by mishmosh** [comment]
Just connected with Henri via Slack. For reference, Github handle is @sternhenri.

Possible outline:
- Content addressing through hashes has become common in many distributed systems
- But they each use a different underlying data structure
- So we built IPLD to make them interoperable
- Enter IPLD
- Story time: how IPLD was conceived & developed
- Examples and use cases
- Near-term roadmap
- Next steps for potential contributors & users.

**Comment by sternhenri** [comment]
Thanks for looping me in @mishmosh! Happy to help on this, sorry for the lag omp. @flyingzumwalt what can I do?

**Comment by mishmosh** [comment]
@sternhenri Can you draft a blog post, tentatively titled "Introducing IPLD"? @flyingzumwalt and I propose the outline above, but feel free to adapt.

**Comment by Ademord** [comment]
Looking forward to your blog posts!
