### ISSUE TITLE
RSS Feed only displays Oldest 20 items

### ISSUE THREAD

**Issue by Plloi** [ipfs/blog#107]
metalsmith-feed by default only adds 20 item to the rss feed. unfortunately it grabs the 20 oldest instead of the 20 newest. 
Also limit doesn't properly take false to remove this.

A workaround could be to add a arbitrarily large limit to the feed.
`.use(feed({'collection': 'posts', 'limit': 1e9}))`

Or reversing the collection this would place most recent 20 in the feed, but it also reverses blog page order
```
  .use(collections({
    posts: {reverse: true}
  }))

```
~~Unless there is a way to reverse the collection order i haven't seen,~~ I'm not exactly a metalsmith wizard.
I plan to post an issue on hurrymaplelad/metalsmith-feed about this as well.

**Comment by Plloi** [comment]
Issue on metalsmith-feed: hurrymaplelad/metalsmith-feed/issues/18

**Comment by Plloi** [comment]
metalsmith-feed has been updated so limiting RSS entries can be removed with:
`.use(feed({'collection': 'posts', 'limit': false}))`

**Comment by Kubuxu** [comment]
This will be affected by https://github.com/ipfs/blog/pull/118 but thanks a lot for it nevertheless.
