### ISSUE TITLE
Blog Post: IIIF on IPFS at the Vatican

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#109]
- Tell the story of the Demos at the Vatican -- IIIF, Images, Interoperability
- Explain the significance -- dynamic data in decentralized applications 
    - mutability (how pubsub is different from IPNS, where pubsub appears in existing web infra)
    - CRDTs vs blockchains
- Present the demo (screen capture)
- Explain the tech -- pubsub, CRDTs (y.js), domain-specific data model (web annotations)
- Walk through the code (key points)
- Future Work
   - leveldown on CRDTs and IPFS pubsub
   - tutorials?
   - ? what am I missing here -- so many things....

**Comment by mishmosh** [comment]
Welcome back and congrats on a great set of presentations & demos. Since event recap posts are somewhat time-sensitive -- will you be able to make time to draft this week?

**Comment by flyingzumwalt** [comment]
Yep. Working on it here: https://docs.google.com/a/protocol.ai/document/d/1B7BJZznfdGsnficm_mdM18zvC2yxDXkJpMuEgBoaya4/edit?usp=sharing

**Comment by mishmosh** [comment]
@flyingzumwalt you said there could be 2 blog posts here but it might actually be 3. Love it.

In thinking about getting one of these posts out into the world:
* The original "Why Cultural Institutions Need IPFS" holds an extremely strong point of view. Could we reserve some of that content for an editorial from Matt in another publication (perhaps another journal or magazine so we can tap their audience), letting the demos shine? An alternate version of "Why Cultural Institutions Need IPFS" (labelled v2 in the doc) addresses some of @hsanjuan's comments and shortens the section (to leave more room for demonstration content). It also attempts to provide a transition into the demos.
* Do you still plan to record screencasts of the demos?
* Do you still want to include a technical writeup or will suffice?

**Comment by diasdavid** [comment]
@mishmosh the demo has been recorded during the IPFS All Hands, here: https://youtu.be/hmAniA6g9D0?t=10m39s :)

**Comment by diasdavid** [comment]
Also, @pgte might have some good descriptions of all the building blocks he created for this, with pointers of how to get started and future work.
