### ISSUE TITLE
Blog Post: Private Networks

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#114]
This is one of the [Top Topics that Need Better Documentation](https://github.com/ipfs/community/issues/199)

Private Networks -- limiting which nodes/peers you will even talk to. This limits which peers can see what you've added to your IPFS node and limits which nodes you will provide blocks to

Currently this feature is implemented in a simple way but needs explanation of what it does & doesn’t do, why it works that way, and a declaration of "future work” that must happen for people to really use the feature

**Comment by Kubuxu** [comment]
Main resources https://github.com/libp2p/specs/pull/10 and https://github.com/ipfs/go-ipfs/issues/3397#issuecomment-284341649 and also me.

**Comment by Mikaela** [comment]
Does https://github.com/ipfs/go-ipfs/issues/4110 have anything to do with this or will it when it happens?

**Comment by Stebalien** [comment]
No. This issue is just about our "private networks" features where uses with a shared key can create a completely separate, encrypted ipfs cluster that never joins the main network.
