### ISSUE TITLE
Merge the blog with ipfs/website, keep the markdown files in ipfs/blog

### ISSUE THREAD

**Issue by daviddias** [ipfs/blog#116]
@lgierth and @VictorBjelkholm have different ideas on if the blog should be merged with the website or not. 

Could you provide your thoughts and discuss it on this thread?

Note: 
- Having a similar style doesn't depend on this

**Comment by VictorBjelkholm** [comment]
From my side, they should be separated as they have two different purposes and should be deployed independently rather than together. However, I don't feel super strong about it, so fine with whatever really.

**Comment by lgierth** [comment]
If they're the same style it's probably easier to merge them. Right now they're supposed to be the same style and codebase, it's just that we never adjusted the deployment for the two. See https://ipfs.io/blog vs. https://ipfs.io/ipns/ipfs.io/blog. The former is nginx rewriting it to blog.ipfs.io, and the latter is the blog as it was supposed to be.

If they're gonna be two different styles anyway, it makes sense to keep them separate.

The ipfs.io/blog vs. blog.ipfs.io thing can be sorted out fine either way.

**Comment by diasdavid** [comment]
Let's make a decision to move this forward. I think our best option is to merge both codebases but keep the markdown files for the blog here, this way we keep a nice clean blog post pipeline separate from all the codebase and styling stuff.

What do you say? 

👍 this comment if you agree.

**Comment by lgierth** [comment]
SGTM :+1:

**Comment by lgierth** [comment]
When merging the too, it would be great if the blog subdirectory were still able to work on its own, e.g. with the assets symlinked underneath it. That way we can continue to support the legacy https://blog.ipfs.io.

**Comment by VictorBjelkholm** [comment]
> merge both codebases but keep the markdown files for the blog here

Sounds good to me, scaffolding and content separated 👍

**Comment by mishmosh** [comment]
Let's say in 6-12 months we want to move blog deploy responsibility off @lgeirth's plate (or at least set up a secondary person). Are we willing to also give that person deploy access to ipfs homepage? 

If yes, then merging as described above (keeping markdown files here) sounds good to mew.

**Comment by lgierth** [comment]
> Let's say in 6-12 months we want to move blog deploy responsibility off @lgeirth's plate

Let's say we completely automate website-ish deploys in the next 3 months ;)

**Comment by diasdavid** [comment]
@mishmosh absolutely. This won't interfere at all. In fact, it might even might result in a solution that will be less error prone as the contributors to the blog (imagine guest blog posts) won't be able to mess with deployment

**Comment by mishmosh** [comment]
Perfect.

**Comment by diasdavid** [comment]
@olizilla @alanshaw let's do this on the next sprint :)

**Comment by jbenet** [comment]
@diasdavid as described by email, keep all the blog content and the ability to generate a web page from it, here, isolated from the main website.
 
it doesn't have to be the same website. if you want to move all the ipfs.io styled website stuff to ipfs/website, that's fine. But keep the content and a way to get a simple website out of it (i.e. have its own static website compiling setup) here.
