### ISSUE TITLE
Deploy the new blog

### ISSUE THREAD

**Issue by diasdavid** [ipfs/blog#120]
@lgierth the code in `master` is now a version of the blog all ported to Hugo 🌟 and it will solve the following issues:

- https://github.com/ipfs/blog/issues/119
- ~~https://github.com/ipfs/blog/issues/22~~ actually this is a problem of blog duplication.

Could you deploy the new version? Thanks!

**Comment by lgierth** [comment]
Someone else already published it...

**Comment by diasdavid** [comment]
Who?
