### ISSUE TITLE
I wanted to publish but I don't have DO access

### ISSUE THREAD

**Issue by diasdavid** [ipfs/blog#129]
![image](https://user-images.githubusercontent.com/1211152/28157737-56250f16-67af-11e7-9b67-61028281a9f4.png)

I've already published and pinned: https://ipfs.io/ipfs/QmT1iDxTPjNiVJrLQv64G8Be2qz3WS7NdiqTFRrHXV9qvg/ but I'm missing DO access to actually update the blog. 

@lgierth could you give me some help?

**Comment by lgierth** [comment]
You need to log into DO and make a new API access token for yourself, then put it into `~/.protocol/digitalocean.token`
