### ISSUE TITLE
Blog is down

### ISSUE THREAD

**Issue by fazo96** [ipfs/blog#13]
https://ipfs.io/blog/ doesn't seem to work :-(

**Comment by jbenet** [comment]
indeed. we broke it. @lgierth maybe just remove the redirect for now? the currently published version of the site has the previous blog there:

- https://ipfs.io/ipfs/QmTgNJEgQaCqRht9KSXNyZsCp2xpHZmBRms28NRMmtcERp/blog/

**Comment by jbenet** [comment]
I just pushed an update to the website: 

- https://ipfs.io/ipfs/QmR7tiySn6vFHcEjBeZNtYGAFh735PJHfEMdVEycj9jAPy

which has some new posts (inc ipscend) but not 4.

**Comment by lgierth** [comment]
the blog is back since yesterday

**Comment by jbenet** [comment]
thanks @lgierth!
