### ISSUE TITLE
Proposal: Editorial Workflow (v2)

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#137]
[_This is not the first discussion of editorial workflow for the IPFS blog. Previous attempts resulted in explicit, regimented workflows that didn't prove useful. Please think of this proposal as a fresh start._]

As the IPFS project grows, and as our activities widen, we have a choice to make about the editorial approach, and overall "voice" of the blog: 

**Option 1**: Make the blog into a tightly controlled, information source that strictly adheres to the voice of _the IPFS project_, with a consistent writing style and consistent content emphasis.

**Option 2**: Treat the blog as a platform that gives visibility to individual IPFS maintainers and IPFS contributors who each have their own interests and writing style.

I prefer option 2. Our recent posts reflect that style. I think we can do even better.

## Reference: Common structure in newsrooms

In most newsrooms you have _writers_, _editors_, an _Editor in Chief_, and a _publisher_. Writers pitch ideas and produce content. Editors figure out which content should be included and are responsible for ensuring quality & consistency. The Editor in  Chief is ultimately responsible for any editorial decisions and for ensuring that editorial policy is followed -- if something bad gets published, the Editor in Chief is responsible for the lapse in quality control. The publisher is not involved in daily operations -- they provide executive-level input (ie. steering the overall focus of coverage) and hold the Editor in Chief accountable.

One key idea is the notion of an _editorial staff_ -- the editors and the editor in chief -- who work together to make sure they put out compelling content with a consistent "_editorial voice_".  Though individual articles and/or columns might have their own style and their own focus, the overall newspaper/platform adheres to some conventions of writing quality, emphasis, fact checking, technical detail, etc.  

Contrast this with a site like [Medium](https://medium.com), where anyone can publish whatever they want. Any consistency to the content is achieved socially, not through editorial policies.

## Proposal

1. Name a group of editors (@diasdavid, @mishmosh, @flyingzumwalt)
2. @jbenet has the role of Publisher
3. Don't have an editor in chief -- let the editors share that responsibility.
4. Encourage maintainers and contributors to submit their own posts. They must pitch their post to an editor before submitting, to make sure it fits with our roadmap and editorial policies. (people have already been doing this informally)
5. Blog posts need to be reviewed and approved by 2 editors before getting published.
6. Add author photos to blog post bylines, to reinforce the idea that the blog is a platform for many voices, with an editorial staff enforcing quality, rather than a unitary voice of "the IPFS".
7. Editors gradually define the editorial policies through trial and error.

**Comment by mishmosh** [comment]
This is a great approach to take the IPFS blog to the next stage. It's fairly close to how we've been operating in recent months. To get publisher, editors, and blog contributors on the same page, I'd like to propose the following addition:

3.5. Editors write a Contributors guide outlining the editorial policies, especially aspects like:
* naming the types of posts we want to encourage
* framing demos in ways that can be relevant & interesting across fields

**Comment by diasdavid** [comment]
Thank you for writing down this proposal, Matt. As @mishmosh pointed out, it is very much like the way we've been operating the blog and what enabled it to have more life. We've been receiving a lot of love for the recent articles.

Shall we consider bringing back the IPFS Newsletter as we design the new Editorial workflow?
