### ISSUE TITLE
Build issues with latest Hugo

### ISSUE THREAD

**Issue by lidel** [ipfs/blog#155]
Hugo  v0.31.1 is used by the CI setup and it works [fine](https://user-images.githubusercontent.com/157609/38552945-060d3172-3cbe-11e8-82be-6f5bbc907d77.png).

However if I try to build it locally with the latest Hugo (v0.38.2) it produces no posts:

> ![screenshot-2018-4-10 ipfs blog 1](https://user-images.githubusercontent.com/157609/38553053-5b5e88f6-3cbe-11e8-9311-ff4f57d37be2.png)

I did not look into details, as the quick workaround was to just use [v0.31.1](https://github.com/gohugoio/hugo/releases/v0.31.1) for this repo.

**Comment by Stebalien** [comment]
I can confirm and I have no idea what's going on.

**Comment by VictorBjelkholm** [comment]
API changes... Gonna give it a try to fix as this is not the first time we encounter this...
