### ISSUE TITLE
Build issue on Windows

### ISSUE THREAD

**Issue by djdv** [ipfs/blog#157]
One of the NPM dependencies `do-wrapper` tests itself during installation, the test uses a wildcard character which is seen as a literal "*", this is preventing the installation from completing.
```
>npm install
...
> do-wrapper@2.2.0 postinstall C:\Users\Dominic\Projects\Go\src\github.com\ipfs\blog\node_modules\do-wrapper
> npm run build && npm run test


> do-wrapper@2.2.0 build C:\Users\Dominic\Projects\Go\src\github.com\ipfs\blog\node_modules\do-wrapper
> tsc src/*.ts --outDir dist/ --module "commonjs"

error TS6053: File 'src/*.ts' not found.
```

**Comment by lgierth** [comment]
You can safely remove the do-wrapper dependency, it's from back when the domains were with Digitalocean. Nowadays Jenkins takes care of updating the dnslink records for us.

**Comment by djdv** [comment]
@lgierth 
Removing `dnslink-deploy` allows the modules to be installed and I can start the server, but I'm still having trouble generating styled pages. For whatever reason `less-plugin-autoprefix` is not being detected.

```
>make build
Unable to interpret argument autoprefix - if it is a plugin (less-plugin-autoprefix), make sure that it is installed under or at the same level as less
make: *** [Makefile:37: css] Error 1
```
It's certainly installed in the same level next to `less` under `node_modules` so I'm not sure where the issue is.

**Comment by djdv** [comment]
I updated NPM to latest, re-fetched the modules and everything seems to be building now.
The original problem with the `do-wrapper` dep inside of `dnslink-deploy` still exists, but removing it locally works around that for now.
