### ISSUE TITLE
Blog post about DHT NAT issues

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#161]
Once @vyzo, @whyrusleeping et al. have resolved this challenge with DHT & NAT (majority of the peers on the DHT can't be dialed due to NAT issues) It would be really cool to have a blog post explaining what we saw happening on the network and how we resolved it.

cc @mgoelzer

**Comment by VictorBjelkholm** [comment]
Think we should do this as a post-mortem as it severely affects the network. Then we can publish that post-mortem together with a friendly description as a blog post.

**Comment by vyzo** [comment]
We haven't fixed it yet!

We should wait until we are ready to roll out a new release with the relays plugged in.
This will has the added advantage of bringing attention to the new release and urging our node operators to upgrade.

**Comment by jessicaschilling** [comment]
Closing: stale issue.
