### ISSUE TITLE
Newsletter: Add subscribe embed to the bottom of newsletter posts

### ISSUE THREAD

**Issue by mikeal** [ipfs/blog#174]
Heya,

We're getting the newsletter up and running again and we'd like to have a "subscribe" embed inserted in the bottom of the blog posts that are from cross-posted weekly newsletters.

I'm not super familiar with hugo so I don't know how easy this is. If you give me some pointers I can probably send a PR myself.

**Comment by lidel** [comment]
I think you want to look at https://github.com/ipfs/blog/blob/master/layouts/post/single.html
We already have JS snippet for embedding Discourse comments after every blog post, I imagine subscribe embed will be similar case.

**Comment by mikeal** [comment]
@lidel is there an easy way to know if the post in question is a weekly newsletter post or not? Ideally I'd like to only add the embed to those posts.

**Comment by lidel** [comment]
hm..  I think hugo creates [tag](https://gohugo.io/content-management/taxonomies/) taxonomy by default, so we could mark them with `newsletter`  tag  by adding this to the header of newsletter posts:

```
tags:
- newsletter
```

Then we could use conditional in `single.html`: 

```
{{ if eq $taxonomy "newsletter" }}
<!-- newsletter subscribe embed  -->
{{ end }}
```

(not tested, syntax may be invalid but the idea should be sound)

**Comment by momack2** [comment]
It'd be nice to embed this page (https://ipfs.us4.list-manage.com/subscribe?u=25473244c7d18b897f5a1ff6b&id=cad54b2230) directly into the place it's linked at the bottom of newsletter posts: https://blog.ipfs.io/weekly-95/ Maybe @renrutnnej you can chat with @jessicaschilling and @rafaelramalho19 about adding this to the backlog for website improvements?

**Comment by jessicaschilling** [comment]
@cwaring -- do you know anything about embeds in Hugo? Is this something you'd have time to tackle?

**Comment by renrutnnej** [comment]
Mailchimp makes it super easy for us to create an embed form, so I can grab that code from the backend for you all to tweak. Let me know!

**Comment by jessicaschilling** [comment]
@renrutnnej Upon looking at this again -- there's a lot of content on that newsletter signup page, and I'd be a little concerned about adding a lot of length to every newsletter blog post that isn't actually newsletter content. What about adding ...
1. A header line that says something like "Like this post? Get our newsletter?"
2. After the "Get the IPFS Weekly ..." copy, a button CTA going to the form

![image](https://user-images.githubusercontent.com/1507828/86373789-04f0af80-bc41-11ea-85d0-9cf7239453d4.png)

If that works for you, the button code is super simple:
`<p><a href="https://ipfs.us4.list-manage.com/subscribe?u=25473244c7d18b897f5a1ff6b&amp;id=cad54b2230" class="button button-primary">Sign up now</a></p>`

You could actually just have that whole header+text+button combo in a scratchpad to cut/paste when you draft those blog posts. Definitely possible to automate according to taxonomy as per @lidel's idea above, but I'm afraid I don't know how to do that in Hugo!

**Comment by renrutnnej** [comment]
This great, thanks @jessicaschilling. Seems like it should be super easy to implement ☺️

**Comment by jessicaschilling** [comment]
Thanks for the update 😊 I'm going to close this issue, but feel free to ping me if you have any problems!
