### ISSUE TITLE
Automate publishing

### ISSUE THREAD

**Issue by mikeal** [ipfs/blog#177]
According to the README all the publishing is done manually and requires access to DigitalOcean.

Is this still true? Can we get this automated like some of the other sites?

**Comment by mikeal** [comment]
Also, can we get a manual publish for the latest.

I tried to run the publishing locally to at least just hand you a CID but it wants to authenticate to npm in order to run so there's some additional assumptions about access controls in the publishing script we haven't even documented.

@diasdavid said that @VictorBjelkholm is the person to ping here :)

**Comment by VictorBjelkholm** [comment]
Hey, it's already setup to be automatic! You can tell by the Status messages in the PR and also the presence of a [Jenkinsfile](https://github.com/ipfs/blog/blob/master/ci/Jenkinsfile).

Is it not up-to-date? [Last commit](https://github.com/ipfs/blog/commit/df4ef086484b274bc4e613a1fcfb110f44c97618) was [successfully built and deployed](https://ci.ipfs.team/job/IPFS/job/blog/job/master/32/)

**Comment by VictorBjelkholm** [comment]
Keep in mind as there are DNS updates, it can take some time for the records to propagate.

**Comment by mikeal** [comment]
Ah, awesome. We should get the README updated :)
