### ISSUE TITLE
IPNS name

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#2]
Will be good to create an ipns name for the blog and keep updating it with every new blog post.

**Comment by jbenet** [comment]
Depends on ipns being robust.

**Comment by whyrusleeping** [comment]
record spec????

**Comment by em-ly** [comment]
Can this issue be closed or is this still a relative discussion?

**Comment by lgierth** [comment]
It's now part of the pages/deployment mini-effort, let's close it. (for context, this will simplify page deployments a lot because we won't have to update DNS records anymore. Same for e.g. the website and dist.ipfs.io.)
