### ISSUE TITLE
Blog post announcing dist.ipfs.io

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#21]
We should write a blog post announcing http://dist.ipfs.io -- and highlight a lot of the cool things ipfs does that makes this site interesting itself:

I think it should:
- [ ] explain the goals of the page (one stop place for all official binaries we distribute)
- [ ] have screenshots (github blog style gifs may be nice)
- [ ] describe criteria for something being added (i.e. should be a product of the IPFS community, should have high quality UX, should be well maintained, anything else?)
- [ ] mention multiple platform (os, arch) downloads
- [ ] mention smart browser user-agent driven button
- [ ] mention site + all binaries are hosted via ipfs itself
- [ ] mention dedup in the resulting dag
- [ ] maybe include a `graphmd` graph of the site, ideally showing dedup
- [ ] mention how site is hosted with IPFS (dnslink, maybe link to a guide)
- [ ] mention that you can view it on ipfs itself, on the local gateway
- [ ] mention using site in local node will make it faster to download versions in the future.
- [ ] mention that it's used by `ipfs-update` itself to update ipfs.
- [ ] mention that you can view it with the browser extensions
- [ ] mention future goal of code signing
- [ ] mention future closer integration with package managers
- [ ] mention future things to be added (like `ipget`, any others?)
- [ ] mention future goal of having {screenshots, gifs, asciinemas} in the page
- [ ] mention dedup on the binaries themselves, if there's any. (add it with `ipfs add -s rabin` for higher likelihood of matches?)
- [ ] mention future goal of importing binaries smartly to enhance chance of dedup
- [ ] invite readers to contribute and file issues at the repo https://github.com/ipfs/distributions 

Would wither @Dignifiedquire or @richardlitt want to write this?

**Comment by RichardLitt** [comment]
Sounds good to me. Deadline for first draft?

**Comment by Dignifiedquire** [comment]
@RichardLitt as you are our official wordsmith how about you do the drafts and I do the reviewing &  explaining things you need to know?

**Comment by RichardLitt** [comment]
Sounds good. Deadline: Thursday night, 9:00pm CET.

**Comment by RichardLitt** [comment]
That deadline was not adhered to; Sorry about that! @dignifiedquire check out the draft.

**Comment by RichardLitt** [comment]
Done!
