### ISSUE TITLE
RSS is broken

### ISSUE THREAD

**Issue by Shaaah** [ipfs/blog#22]
I'm trying to add the blog rrs fedd to my aggregator, but it just doesn't work.

Tried the validator it looks like there are [some problem](http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fipfs.io%2Fblog%2Frss.xml)

**Comment by ARezaK** [comment]
I would like to follow along as well with the rss feed. It looks like you have the necessary packages setup with metalsmith, just not sure why it isn't working.

**Comment by dan-madaket** [comment]
Yes, came here looking for this!

**Comment by JayBrown** [comment]
RSS loads from feed URL https://ipfs.io/./rss.xml in Vienna, but only until 2016-05-31, so there's something definitely not right.

But what about `ipfs pubsub`? Wouldn't that be better than RSS eventually?

**Comment by mishmosh** [comment]
Debugging occurring in #107

**Comment by diasdavid** [comment]
Unfortunately, seems that this didn't get fix with the #118 

![image](https://user-images.githubusercontent.com/1211152/28746165-a374e352-743b-11e7-89d2-353abbd53699.png)

@alanshaw @richsilv any thoughts on this? I might have assumed incorrectly that moving to Hugo would fix this, do you know what needs to happen to make it work?

**Comment by alanshaw** [comment]
I think this is now resolved - at least, it is working for me 😛

**Comment by diasdavid** [comment]
Almost, tried it out and noticed there is a top article that is just the template:

![image](https://user-images.githubusercontent.com/1211152/29458928-bc30d126-8421-11e7-8965-f918aecebd5a.png)

**Comment by diasdavid** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fipfs.io%2Fblog%2Findex.xml shows multiple errors
