### ISSUE TITLE
Add an explainer to the readme for how to add images to blog posts?

### ISSUE THREAD

**Issue by momack2** [ipfs/blog#232]
Since we frequently want to embed videos or images in our blog posts, it would be great to document how to insert an image into a blog post (in addition to normal markdown). There are different examples in past blog posts (some adding it to an "/imgs" folder, some pulling from ipfs). A quick "how to" would be useful to document the options and pros/cons!

**Comment by momack2** [comment]
What I just did (which hopefully works):
1. Create a folder with the name of the blog post in the “static” folder
2. Create an img folder and upload desired pngs 
3. Use markdown to reference the img in your blog post as ![subtext](img/<name of your png>)

**Comment by jessicaschilling** [comment]
Closing, as this is part of the overall Forestry workflow in https://github.com/ipfs/ipfs-blog.
