### ISSUE TITLE
Some links download .md files

### ISSUE THREAD

**Issue by autonome** [ipfs/blog#246]
I found a link to https://blog.ipfs.io/37-ipfs-conf-dev-meetings-and-user-registry.md in a Github conversation, but it just downloads the markdown file instead of rendering it.

Any ideas why that one? I haven't tested to see which others are doing this also.

**Comment by autonome** [comment]
Hm, in the blog index, it's the only one w/ .md extension.

S replacing with slash...

https://blog.ipfs.io/37-ipfs-conf-dev-meetings-and-user-registry/

gets...

ipfs resolve -r /ipns/blog.ipfs.io/37-ipfs-conf-dev-meetings-and-user-registry/: no link named "37-ipfs-conf-dev-meetings-and-user-registry" under QmQR5hdRyFkmoHNprUqAHKfXe3fJstFvEKhrnbyFv54jfj

**Comment by autonome** [comment]
the original doc: https://github.com/ipfs/blog/blob/master/content/post/026-ipfs-conf-dev-meetings-and-user-registry.md

**Comment by Stebalien** [comment]
This has now been fixed.
