### ISSUE TITLE
Blog post describing 0.4.0 changes

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#28]
We need a blog post detailing 0.4.0 improvements. They're big. Who can pick this up? maybe @RichardLitt with help of @whyrusleeping and @diasdavid? others interested?

**Comment by diasdavid** [comment]
I'm happy to help, from the top of my head, we have:

- files api
  - flush or no flush options
  - speed improvements on add
- object api
  - new methods (subcommands)
- js-ipfs-api
  - new version to match the 0.4.0
- repo
  - new repo structure
- things that are now possible
  - registry-mirror

**Comment by RichardLitt** [comment]
Relevant to https://github.com/ipfs/go-ipfs/issues/2336

**Comment by whyrusleeping** [comment]
@kyledrake had started this, i think he should have something saved somewhere
