### ISSUE TITLE
Perform a design audit on the blog

### ISSUE THREAD

**Issue by ericronne** [ipfs/blog#295]
See whether we can't execute some quick design improvements.

**Comment by momack2** [comment]
IPFS Blog:
![image](https://user-images.githubusercontent.com/618519/77981132-ee436100-72bd-11ea-880e-86a1217bf2af.png)

Filecoin blog:
![image](https://user-images.githubusercontent.com/618519/77981173-0c10c600-72be-11ea-81cc-a8d179e0a17f.png)

I'd be great to get some small tweaks to make these blog posts stand out more easily. I think using more imagery like the Filecoin blog does is a great way to make headlines more personal/interesting!

**Comment by johnnymatthews** [comment]
Threw this together (using random placeholder images). Thoughts?

![Screenshot_2020-04-01 IPFS Blog](https://user-images.githubusercontent.com/9611008/78184375-6719f880-7437-11ea-8d1d-37614d459e98.png)

Having a bunch of images on the screen would mean we'd have to paginate things a little bit. We'd also have to assign each article a picture.

**Comment by momack2** [comment]
J'adore!! I think it's a huge improvement over the previous one. Would love to make the titles 2x bigger though. I bet @renrutnnej or I can help source the right header images too (would love to have a design image for the IPFS Weekly Newsletter for both this and Mailchimp!)

**Comment by johnnymatthews** [comment]
Pushed my changes to [`ipfs/blog:blog-picture-list`](https://github.com/ipfs/blog/tree/blog-picture-list). I don't think there's any CI stuff to preview it, so here's a screenshot:

![Screenshot_2020-04-02 IPFS Blog](https://user-images.githubusercontent.com/9611008/78213751-82115a80-7481-11ea-97a2-5688ec302348.png)

I reduced the columns to 2, and added the placeholder image. If there's no `header_image` variable declared in the front-matter, then that image will show.

**Comment by renrutnnej** [comment]
Happy to help! Excited that the IPFS blog is getting the royal treatment 🥰

As far as a header image for the weekly, I think I'll need to put in a design request for that one. The closest thing I have currently is some open sourced artwork and/or our logo 😂

**Comment by momack2** [comment]
@johnnymatthews what is the structure for adding in the images I noted in this sheet: https://docs.google.com/spreadsheets/d/1q3dNlFcxlsX1a666GeyaKBCJ7A4H9tLwSHgSeRR2MEQ/edit#gid=0?

**Comment by johnnymatthews** [comment]
I'll write a script to download the images that are in the spreadsheet, and add them to the appropriate blog post. I'll use a placeholder for anything with `IPFS Weekly` in the name until @renrutnnej finds a cool picture for those. Everything else (posts that aren't an IPFS Weekly and don't have an image assigned), will default back to the space-IPFS placeholder used above. Shouldn't take too long.

**Comment by johnnymatthews** [comment]
Just thought, we might run into an issue with page-load times if we're serving a bunch of images. Pretty sure [Hugo deals with pagination](https://gohugo.io/templates/pagination/) fairly well though. I'll take a look.

**Comment by johnnymatthews** [comment]
[PR 391 here](https://github.com/ipfs/blog/pull/391).

**Comment by jessicaschilling** [comment]
Closing this, since this round of visual changes has been implemented. We can address further improvements in their own issues as they come up.
