### ISSUE TITLE
Needs relative urls

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#3]
I'm using `hugo` at the moment. but it's not wanting relative urls. see https://github.com/spf13/hugo/issues/1104

**Comment by jbenet** [comment]
maybe there's a way to make it do relative urls correctly. not sure.

**Comment by insanity54** [comment]
tinkering

**Comment by jbenet** [comment]
thanks for taking a look @insanity54

**Comment by jbenet** [comment]
Given https://github.com/spf13/hugo/issues/1104#issuecomment-99261114 we probably should just use something other than hugo. :/

**Comment by jbenet** [comment]
Or maybe we can rewrite the urls as a post-processing step after hugo does it's work. we'd have to:

- resolve the shortest path to the target (e.g. `/post/index.html` should link directly to `./0-hello-worlds/`instead of to `../post/0-hello-worlds/`) 
- replace all links (`<a href>`, `<rel>`, `<img>`, etc.)

**Comment by jbenet** [comment]
Ok, switched to [metalsmith](http://metalsmith.io) and things work now. i borrowed most of the stuff behind https://github.com/ipfs/website
