### ISSUE TITLE
Circle CI jobs being built but not deployed

### ISSUE THREAD

**Issue by autonome** [ipfs/blog#312]
Pushed #311 and noticed it never went live on the blog.

Looks like #307 hit this too.

I poked Infra on Slack.

**Comment by autonome** [comment]
Weeks of failed jobs due to permissions problem. Looks like maybe only pushes from admins deploy...

**Comment by jessicaschilling** [comment]
I just ran into this on #329 too. @autonome or @daviddias - what’s the manual way around this? I can’t deploy ... :(

**Comment by autonome** [comment]
For posterity, this is still happening, showed up in #329.

**Comment by olizilla** [comment]
The "fix" for this is that anyone who does the merge needs to be subscribed to the circle CI builds for the repo, otherwise it seems to fail to match the user as someone who has permission to trigger the build.

**Comment by jessicaschilling** [comment]
Closing, as this process is moving to Fleek deploy in https://github.com/ipfs/ipfs-blog.
