### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by jennwrites** [ipfs/blog#349]
Is it possible to see how many people subscribe to the blog via RSS?

**Comment by lidel** [comment]
Not sure.  Most of proprietary services provide a number that is some sort of "daily average" (example: [squarespace](https://blog.squarespace.com/blog/2008/1/31/understanding-rss-feed-subscriber-stats.html)), there is also https://feedburner.google.com which provides extensive stats, but it requires feed to be routed via Google servers :(

Without using any third party, the best we could do is to count requests for the feed at https://blog.ipfs.io/index.xml made every day.  

@olizilla thoughts on how feasible this would be? Are we already aggregating logs per URL?

**Comment by jessicaschilling** [comment]
Closing in favor of adding @lidel's suggestion to our overall Countly metrics under https://github.com/ipfs/ipfs-blog/issues/16.
