### ISSUE TITLE
numbers disappearing from blog titles

### ISSUE THREAD

**Issue by renrutnnej** [ipfs/blog#355]
<img width="495" alt="Screen Shot 2020-01-28 at 1 46 23 PM" src="https://user-images.githubusercontent.com/2582805/73299383-b6903e00-41d4-11ea-9575-9ca0549d8641.png">

Some of the IPFS Weekly blog posts show the issue # but the recent ones do not. 🤔

**Comment by alanshaw** [comment]
@renrutnnej please note the fix in https://github.com/ipfs/blog/pull/356 - would you mind sending a PR to fix the latest one?

**Comment by renrutnnej** [comment]
@alanshaw yep, thanks again!
