### ISSUE TITLE
Link to blog doesn't work on local gateways

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/blog#36]
Please see fs:/ipns/ipfs.io/blog on local gateway.

@whyrusleeping confirmed that

It should probably be issue on website.

**Comment by lgierth** [comment]
yeah the way it's right now, it's /ipns/blog.ipfs.io

**Comment by RichardLitt** [comment]
@Kubuxu Can this be closed?

**Comment by Kubuxu** [comment]
I think yes.
