### ISSUE TITLE
Fix ipfs.io/blog/* links loaded via DNSLink

### ISSUE THREAD

**Issue by lidel** [ipfs/blog#360]
We've moved blog to `blog.ipfs.io` and fixed most of problems in https://github.com/ipfs/blog/pull/182 but links to `ipfs.io/blog/*` are still around due to the way Discourse integration was done for comments.

Example: try opening https://ipfs.io/blog/2020-01-30-go-ipfs-0-4-23/ with ipfs-companion's redirect to local gateway enabled.

Links under `ipfs.io/blog/*` break when DNSLink for ipfs.io is resolved:

→  `dnslink(https://ipfs.io/blog/2020-01-30-go-ipfs-0-4-23/)`
← `ipfs resolve -r /ipns/ipfs.io/blog/2020-01-30-go-ipfs-0-4-23/: no link named "2020-01-30-go-ipfs-0-4-23" under bafybeics2j3x4qcn3365docj4f5xfe7gwlbakds7x3it63okc572imyb4e`

This means we are unable to sovle this at Nginx level.

I think we need two fixes:

- [x] https://github.com/ipfs-shipyard/ipfs-companion/pull/844: adding rule redirecting ipfs.io/blog → blog.ipfs.io should be harmless and would remove frustration from new users who tried to visit the page
  - fix specific to ipfs-companion, won't work in other user agents that are capable of resolving DNSLink
  - mitigates the problem of existing links

- [x] https://github.com/ipfs/blog/pull/372 (for blog.ipfs.io website): add JS to every page that detects the page was loaded from `ipfs.io/blog` and redirects to URL at `blog.ipfs.io`
  - fixes URLs for everyone, not just companion users
  - this way people won't be able to copy&paste invalid links (removes the problem going forward)

<del>This could be good "first issue". 
Comment below if you'd like to work on this, I'll be happy to provide guidance.</del>

**Comment by lidel** [comment]
I've implemented both fixes, see https://github.com/ipfs/blog/pull/372 & https://github.com/ipfs-shipyard/ipfs-companion/pull/844

**Comment by jessicaschilling** [comment]
@lidel @olizilla This makes sense to me!

**Comment by olizilla** [comment]
> links to ipfs.io/blog/* are still around due to the way Discourse integration was done for comments.

Can we fix discord?

**Comment by jessicaschilling** [comment]
Pretty sure admins can search/replace, but it’d have to be done manually and I’m a bit concerned about the optics of editing community posts. We’ll have the same issue with docs URLs once the legacy docs are deprecated, and the plan was to be really good about redirects on the infra side (we’re talking about something like 55 pages in that case).

**Comment by lidel** [comment]
There is one sensitive place: the code responsible for displaying comments on the blog.

The tricky line is at:

https://github.com/ipfs/blog/blob/cb4f40549b49efdf5fcefcb49badf50c9dad0682/layouts/post/single.html#L26

AFAIK we can't change this URL for existing posts because it would create new thread for each one, and lose connection to existing comments. 

The `'https://ipfs.io/blog/{{ .URL }}'` needs to remain as a way of loading comments for existing posts.

What we could do is to add a quick check  if blogpost "publishing date" is after a certain date (eg. make it 1st of March 2020) and switch comment URL to `https://blog.ipfs.io/{{ .URL }}`. This way new threads for new posts would use safe domain name, finally removing the problem going forward.

Y/n? (I can PR)

**Comment by olizilla** [comment]
That is madness... how do people migrate these things... I can see https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

says you can point people to existing discussions if you use the discourseUrl, but it's much the same problem...this is the worst.

**Comment by lidel** [comment]
@olizilla yes, it is pretty unfortunate :(

Don't think we can fix this for historical discussion threads without changing values in SQL table of Discourse somewhere. 

Perhaps fixing future posts is enough?
See a fix proposed in https://github.com/ipfs/blog/pull/375
