### ISSUE TITLE
Schedule a blog post for automatic publication

### ISSUE THREAD

**Issue by alanshaw** [ipfs/blog#365]
See https://github.com/ipfs/blog/pull/364

A nightly Github action to run CI would allow us to schedule blog posts to be automatically published on the given date/time.

**Comment by mikeal** [comment]
You could just run it hourly, as long as the script finishes in under an hour there’s no harm in giving you some more granularity on the time.

I have a half dozen repos with hourly actions and the only time they get into trouble is when they take longer than an hour to run.
