### ISSUE TITLE
Update link in the repo description

### ISSUE THREAD

**Issue by lidel** [ipfs/blog#377]
> See #360  for wider context

Who has admin rights and can change `ipfs.io/blog` to `blog.ipfs.io` in this repo's description?
@olizilla?

> ![Screenshot_2020-02-18 ipfs blog](https://user-images.githubusercontent.com/157609/74783238-40cb3f80-5273-11ea-81a0-a1f475f1de11.png)

**Comment by hsanjuan** [comment]
I do
