### ISSUE TITLE
The Blog has a hard depdendency on hello.myfonts.net

### ISSUE THREAD

**Issue by mburns** [ipfs/blog#398]
https://github.com/ipfs/blog/blob/master/less/components/typography.less#L43

# Description

[New builds in Circle are failing](https://app.circleci.com/pipelines/github/ipfs/blog/954/workflows/6258dace-3fc0-4416-865f-9a5604a9b3b7/jobs/1724) the `make` step because it cannot load the external dependency https://hello.myfonts.net/count/314625.less

Looks like the myfonts.net site is offline at the time of this writing: http://issitedownrightnow.com/status/hello.myfonts.net

The Internet Archive has a snapshot, fwiw: https://web.archive.org/web/20181010064643/hello.myfonts.net/count/314625

# Ask

Can we host this file in IPFS instead? /CC @alanshaw seeing as you touched it last... 2+ years ago :)

**Comment by johnnymatthews** [comment]
I'll take this one.

**Comment by johnnymatthews** [comment]
Fixed in 55ed32a93f58979c76be42c76b0c7babd0d4665a
