### ISSUE TITLE
No pagination

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#400]
Love the new index -- much nicer!

- I request we remove pagination from the blog index though
- Pagination on the blog makes it very hard to find content. Many great blogs are moving to no pagination (long) pages. This should be OK from a loading perspective, as browsers only really load the images once scrolling happens.
- if we _really need_ pagination, then please make the full listing another page linked to from the blog landing page

**Comment by jbenet** [comment]
Great examples:
- https://openai.com/blog/
- https://distill.pub/
- https://colah.github.io/

**Comment by jessicaschilling** [comment]
Closing this issue, since we're removing pagination from the blog in our replatforming work!
