### ISSUE TITLE
3x grid

### ISSUE THREAD

**Issue by jbenet** [ipfs/blog#401]
Really love the new grid, thank you for doing that! much nicer way to see the blog.

Request: blogs with 3x grids are pretty good. Right now the images are very big, could be smaller (to fit a third). At least this in the higher resolutions (full laptop screen width).

Example:
- https://blog.textile.io/

Demo

![image](https://user-images.githubusercontent.com/138401/79976959-5b2bc000-8452-11ea-87cc-1de4504cc9fa.png)

**Comment by johnnymatthews** [comment]
Sure. I'll take this one. I'm hoping it just requires changing a class somewhere.

**Comment by jessicaschilling** [comment]
@johnnymatthews -- thanks!

**Comment by johnnymatthews** [comment]
Here we go:

![image](https://user-images.githubusercontent.com/9611008/86287644-864f3000-bbb6-11ea-8278-93629bf13bce.png)
