### ISSUE TITLE
Make sure all blog posts get a directory

### ISSUE THREAD

**Issue by Stebalien** [ipfs/blog#423]
It looks like some blog posts (e.g., the recent gossipsub one) are being written as flat html files with no `.html` extension in the `posts` directory. Instead, we _should_ be creating one directory per post, with an `index.html` file in each directory.

This bug means go-ipfs is failing to correctly detect the content type. In this case, go-ipfs sees the `.1` and thinks the gossipsub post is a man page. That means anyone using IPFS companion can't access https://blog.ipfs.io/2020-05-20-gossipsub-v1.1.

**Comment by Stebalien** [comment]
![download](https://user-images.githubusercontent.com/310393/83673334-7a0e8d80-a58c-11ea-96c0-53470c096c75.png)

**Comment by autonome** [comment]
Making all blog posts a directory is likely overly prescriptive.

Band-aid is to rename the file.

Fix is to find out why/where the file extension creation is failing - should confirm if it's an actual Hugo bug.

**Comment by Stebalien** [comment]
Ah, now I see the issue. Hugo is saying "you've specified an extension here, this must be a file!". So it creates a file instead of a directory with an index.html file.

**Comment by Stebalien** [comment]
Looks like @hugomrdias was right. We just needed these URLs to start and end with a slash.
