### ISSUE TITLE
index page header images should be pulled from post assets dir

### ISSUE THREAD

**Issue by autonome** [ipfs/blog#435]
Right now we have *three* separate places in the filesystem where a post's data is stored, if a post has images:

* content/post/*.md
* static/imgs/*.*
* static/header_images/*.*

I'd like to have the blog header image frontmatter field `header_image` just pull from the post assets folder (and have an assets folder per post), instead of a special folder for index page header images. This allows all a posts assets to consolidated into one place in a standard way, both making authoring more straightforward and also a bit of future-proofing for migrations.

**Comment by jessicaschilling** [comment]
Closing, as this is mitigated under the new Forestry workflow in https://github.com/ipfs/ipfs-blog.
