### ISSUE TITLE
Blog header images on index page should be autocentered, not require exact aspect ratio

### ISSUE THREAD

**Issue by autonome** [ipfs/blog#437]
Right now, if a blog post header image on the index page (blog.ipfs.io) is not aspect ratio 2:1, it's either too tall or short.

This means a few things:

* we have to make custom images for the index page blog post header and the actual blog post header when 2:1 doesn't work on the post itself.

* it's error prone as authors don't know this rule and there's no validation in place that stops them from committing a wrongly sized image (and maybe no docs either, dunno).

* since we don't have a way to easily preview the site with images, we instead have to post, wait for CI, check the live site, and then go back and fix.

Instead, we should have each image cropped+centered using CSS, so that the exact aspect ratio doesn't matter. This will reduce error by authors, and wrongly sized images on the live site will still look ok in general.

(Separately, I'd like to have the blog header image frontmatter field just pull from the post assets folder, instead of a special folder for index page header images, as we now have *three* separate places in the filesystem where a post's data is stored. Filed #435 for this.)

**Comment by jessicaschilling** [comment]
Forestry workflow in https://github.com/ipfs/ipfs-blog uses 2:1 aspect ratio for both card images and hero images, plus includes live preview and a [crop/scale tool](https://ipfs-blog.on.fleek.co/image-crop/). Closing this issue.
