### ISSUE TITLE
Update old blog links

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/blog#47]
@Porco-Rosso pointed out [here](https://github.com/ipfs/newsletter/issues/7#issuecomment-221115304) that the old links to http://tinyletter.com/ipfsweekly are now broken in the old blogs. We should update them to https://tinyletter.com/ipfsnewsletter. 

Or, could we use an IPFS path and point it at the newsletter? @lgierth?

**Comment by songproducer** [comment]
Contact link on home page as well:
Path Resolve error: no link named "contact" under QmTzQ1JRkWErjk39mryYw2WVaphAZNAREyMchXzYQ7c15n

Also on this page:
https://ipfs.io/docs/
Project directory status board - http://project-repos.ipfs.io/

**Comment by RichardLitt** [comment]
@lgierth Any word on this?

**Comment by em-ly** [comment]
What is the status with this bug? Why is it being sent to Lars? @RichardLitt is there a work around that we can come up with ourselves? How big of a priority is this?

**Comment by RichardLitt** [comment]
Status: Still a bug. 
Why lars: Because I need feedback on it. I'm not sure we should go through and adjust the old blog links, because it might break some of the hashes - I think? I don't know exactly if we _can_ edit old posts easily. I also can't update anything on the live website. Lars is my go-to "let's push stuff to the website" person.
Workaround: No. I can't push stuff. 
Priority: Well, it's broken. Whenever Lars can get to it would be good.

**Comment by RichardLitt** [comment]
@lgierth Thoughts?

**Comment by mishmosh** [comment]
@lgierth Some links in old blog posts go to an outdated newsletter. Would there be any problems (eg with hashes) if we updated those links to the current newsletter signup (https://tinyletter.com/ipfsnewsletter)?

**Comment by lgierth** [comment]
@mishmosh That's fine, we can just change them

**Comment by tapaswenipathak** [comment]
Hi folks - Is the ticket still open, can I work on the ticket?

**Comment by Stebalien** [comment]
@tapaswenipathak yes, it's still an issue. A PR would be awesome!
