### ISSUE TITLE
Discussion: Forestry.io integration

### ISSUE THREAD

**Issue by Ricardo-Silva91** [ipfs/blog#493]
Hello! I'm opening this issue so we can discuss the integration of [forestry.io](https://forestry.io/) in this repository.
One major concern for this is forestry's limitation regarding media uploads (it stores all the images in the same directory, or in a [date]/[img] structure, which is still different from the current [post_url]/[img] structure).

This does not block the old way of uploading posts (as long as the path to the media is correct, it will show up without problems 😌), but it may cause some problems for forestry only editors, as they will not be able to find the media.

I'm working on the PR that will setup the forestry integration, along with the relevant snippets for less tech oriented editors to use, but while that's going on this issue could be used to reach a consensus for the best approach 😄.

**Comment by Ricardo-Silva91** [comment]
@autonome , please @ anybody whose eyes you would like to be looking at this 😊

**Comment by momack2** [comment]
Filecoin stores all images in the same "blog" folder, and it hasn't been an issue there. I'd be fine with a migration that switches to that pattern (ideally consistently so that we can copy old patterns into new blog posts without worry).
