### ISSUE TITLE
Implementing a label system

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/blog#57]
We are going to start using GitHub labels to more effectively maintain this repository. It is important that the labels:
- are maximally useful
- are Easily understood without reference
- clearly say where it is and what it needs

Here are my proposals for the labels:
- stage: idea
  - needs assignments
- stage: skeleton
- stage: research
- stage: writing
  - needs rewrite
- stage: review
  - needs content review
  - needs tech review
  - needs cohesion review
  - needs mech review
  - needs sign off
- stage: ready

The stages will also conform to the Waffle board at https://waffle.io/ipfs/blog. 

I propose that all 'needs review' are shades of blue, all 'stages' are shades of yellow, except for 'stage: ready' (green) and 'stage: idea' (pink).

If this sounds good, I'll go ahead and create them and put them on the posts currently in the system. These are:
- Static Web Publishing #31 ----- "stage: writing" "needs rewrite" owner: @RichardLitt
- ipfs.pics blog post #15 ----- "stage: review" "needs sign off" reviewer: @jbenet
- quick install of ipfs #8 ----- "stage: writing" "needs rewrite" owner: @RichardLitt

**Comment by aistich** [comment]
These sound good to me!

**Comment by em-ly** [comment]
I think the natural flow is for once an idea has been assigned it moves from "needs assigned" to  "stage: skeleton" 

@aistich Can you go through the open issues and start tagging appropriately?

Let's also get the blog ideas that have already been assigned written out as issues and get the tagging going so that we can see what's on the board.

**Comment by aistich** [comment]
@em_ly I can start tagging on Tuesday-

However, I want to make sure there is a pick-up indicator.

There is a definite stage between the idea being assigned and the skeleton
being actually worked on.

Having that tag makes it easier to see if someone has let an article drop
in the early stages.

It may also be a good idea to create a tag for people who need help on
their post like an "help needed" label for use if someone no longer feels
able to write their piece or gets stuck at a stage before they are ready
for technical review.


On Thu, Jun 30, 2016 at 12:31 AM, em-ly <notifications@github.com> wrote:

> I think the natural flow is for once an idea has been assigned it moves
> from "needs assigned" to "stage: skeleton"
>
> @aistich <https://github.com/aistich> Can you go through the open issues
> and start tagging appropriately?
>
> Let's also get the blog ideas that have already been assigned written out
> as issues and get the tagging going so that we can see what's on the board.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ipfs/blog/issues/57#issuecomment-229581776>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ASpYnsI-B0AbQsPPrVLMO0NrrUNaaCvkks5qQ3DRgaJpZM4JBIe1>
> .
>



-- 
Ariel Stich
Operations Manager
Protocol Labs

**Comment by RichardLitt** [comment]
> Maybe add one that indicated the idea has been assigned, but the owner has not begun work?
> There is a definite stage between the idea being assigned and the skeleton
being actually worked on.
> Having that tag makes it easier to see if someone has let an article drop
in the early stages.

I'm not sure there needs to be this one; you can assign people directly, and from then on, that is their responsibility. How they juggle that isn't something we should label, I don't think? Just like `writing` and  `research`, this is going to be a process. If someone hasn't committed anything to the blog within a few days, it would be good to ping them - you can tell this from the history in the issue // PR, I think. 

> @aistich Can you go through the open issues and start tagging appropriately?

None of the open issues are actually topic related. We should have a `topic` label, maybe, to show that it goes with these. The other issues are currently all `meta` or `bugs` in the actual blog mechanics. 

> Let's also get the blog ideas that have already been assigned written out as issues and get the tagging going so that we can see what's on the board.

This sounds good to me.

**Comment by RichardLitt** [comment]
> It may also be a good idea to create a tag for people who need help on
their post like an "help needed" label for use if someone no longer feels
able to write their piece or gets stuck at a stage before they are ready
for technical review.

Like all of the IPFS repositories, this one has a `help wanted` tag. This should be used in those cases. The `difficulty: easy|medium|hard` options are also here.

**Comment by RichardLitt** [comment]
I've created all of the labels, and implemented it on Waffle. 

@aistich - when an article is started as a PR, it will move automatically to Skeleton. You should be able to use this as an indicator that the work has begun or not. 

Regarding opening issues for the current blog posts: I don't think this is unnecessary. A blog post will remain as an open PR until it is published - because of this, might be a good idea to talk about the entire process in the PR. I think having an issue and a PR for each post might get a bit confusing; the initial issue should perhaps be closed when a PR is opened?

**Comment by em-ly** [comment]
So, the agreed upon flow was that each post should start as an "idea" issue, to allow discussion before it becomes a blog post. As it moves from IDEA to SKELETON, the issue will be closed, linking to a correlating PR opened for that blog post.

**Comment by em-ly** [comment]
Also, I would say this was successfully completed. 😃 Thanks, @RichardLitt! Feel free to close.

**Comment by RichardLitt** [comment]
Reopened because I think this should be closed when the workflow in this issue is written in a Markdown.  Good information here.

**Comment by mishmosh** [comment]
Workflow is in https://github.com/ipfs/blog/blob/master/PIPELINE.md.
