### ISSUE TITLE
List of inspirational blogs

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/blog#59]
This should be a list of other blogs in the area that are inspiring: either on their execution, because of their writing, or because of their design. What inspires you about it? What do you think we should have in IPFS?

**Comment by em-ly** [comment]
Great topic to have running.

Consensys just sent out a great news letter: http://us11.campaign-archive2.com/?u=947c9b18fc27e0b00fc2ad055&id=fe8f01928b&e=200297204e

I think these are also some great examples of great documentation:
https://www.ethereum.org/greeter
http://www.ethdocs.org/en/latest/
https://fishshell.com/docs/current/tutorial.html
https://docs.docker.com/docker-for-mac/
https://tour.golang.org/welcome/1

**Comment by jbenet** [comment]
Good:
- https://storystudio.oculus.com/en-us/blog/the-problem-with-reality/
- https://openai.com/blog/generative-models/
- https://0fps.net/

Epically good:
- http://worrydream.com/LadderOfAbstraction/
- http://worrydream.com/ClimateChange/
