### ISSUE TITLE
Blueyard Berlin Meetup 

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/blog#64]
We should have a post about how the Decentralized and Encrypted Conference went in Berlin. 

https://github.com/ipfs/community/issues/127

**Comment by lgierth** [comment]
I think this doesn't make sense anymore

**Comment by RichardLitt** [comment]
I agree with you. Oughtn't we to have some record of it, however?

**Comment by lgierth** [comment]
Like, adding it to some events-we-attended list? I was just looking to close a few open issues :)

**Comment by RichardLitt** [comment]
See ipfs/community#198.
