### ISSUE TITLE
Decentralized Web Summit Roundup

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/blog#65]
Started in [this comment](https://github.com/ipfs/blog/issues/7#issuecomment-225761374):

Coming out of the Decentralized Web Conference
- [ ] IPFS Internet Archives - Using IPFS for Permanent Data Storage
- [ ]  Libp2p
- [ ] js-ipfs is IPFS ON THE BROWSER. It's finally here! It is a full implementation of IPFS in javascript,    and it works...
- [ ] Orbitz demo

@whyrusleeping @diasdavid  I believe you were working on this: am I right in that?

**Comment by lgierth** [comment]
I think this doesn't make sense anymore either

**Comment by RichardLitt** [comment]
@whyrusleeping and @diasdavid - was anything written about this?

**Comment by mishmosh** [comment]
Closing b/c window of opportunity has ended.
