### ISSUE TITLE
IPFS Workshop Lisbon Round-up

### ISSUE THREAD

**Issue by aistich** [ipfs/blog#68]
We need someone to do a short write up on the highlights of the workshop.
@diasdavid is producing a video from the workshop- 
@RichardLitt can  you review that and do a short write up to post and point to that video?

**Comment by RichardLitt** [comment]
I probably shouldn't; I wasn't there, and the streamed quality was not good, so I wasn't able to attend any of the sessions effectively. 

I feel that people who were there could better stub out how it went, and I am happy to work with them and/or edit those posts. I'm not sure how exemplary of the entire event @diasdavid's video will be.

**Comment by diasdavid** [comment]
I just produced the maps on IPFS talk https://www.youtube.com/watch?v=ULZZj3GEqew. I know you saw me editing other parts + making an intro, but it was more as something I do that I really enjoy, unfortunately, editing the whole workshop would take me a considerable amount of time and although I really enjoy doing that, I understand that my time is now better spent just doing js-ipfs things.

**Comment by aistich** [comment]
@RichardLitt who do you think would be a good candidate for the write up?
@diasdavid sorry- was unsure of what would be on there.

**Comment by RichardLitt** [comment]
I'm not sure. There might be a member of the community we could ask, who was there? I don't think @diasdavid has the time, nor @whyrusleeping. I'm happy to review any quick notes they draw up, though.

**Comment by skylarnorris** [comment]
@jbenet can you weigh in on the following:
- [ ] whether it should be public knowledge that certain attendees were sponsored 
- [ ] whether those candidates should be asked to write a blog

**Comment by mishmosh** [comment]
Closing because window of opportunity ended.
