### ISSUE TITLE
Suggestion Blog admin panel 

### ISSUE THREAD

**Issue by Snarkly** [ipfs/blog#71]
Non-coders will never use IPFS Blog if they have to code stuff into it. The blog needs an admin panel like wordpress for non-coders. I've shown ZeroNet to multiple people who can't code and they all said they wouldn't use it for the same reason, it has no admin panel for the blog. Please DON'T follow in ZeroNet's footsteps, create an admin panel for IPFS Blog.

**Comment by lgierth** [comment]
This is just the project's blog at https://ipfs.io/blog -- but I agree, blogging applications on top of IPFS are definitely possible!

**Comment by RichardLitt** [comment]
@Snarkly Want to reopen this in ipfs/notes? Good idea!
