### ISSUE TITLE
Blog Post: "Tell us about your IPFS-based projects"

### ISSUE THREAD

**Issue by ghost** [ipfs/blog#77]
- we've lost overview of all the cool stuff out there
- tell us at ipfs/awesome-ipfs
- then highlight 2 or 3 neat projects, e.g. maps.ipfs.io, uberpen, and infura

**Comment by em-ly** [comment]
Side note: I LOVE THIS IDEA!! Thanks, @lgierth!!!

**Comment by RichardLitt** [comment]
@lgierth Why don't we just write a blurb about those three projects? I'm unaware of the second two, and I'm not sure where maps.ipfs.io is. Would you be able to sit down and talk about them with me for ten minutes, at some point?

**Comment by jessicaschilling** [comment]
Closing: stale issue, and being worked on in great detail in other areas (ecosystem directory, etc).
