### ISSUE TITLE
Quarterly roadmap/milestones blog post

### ISSUE THREAD

**Issue by lgierth** [ipfs/blog#84]
Now that we have good practices around roadmaps and milestones, it would be neat to write a blog post at the beginning of each quarter, detailing the high level goals, and going down to each milestone. The exact dates of the milestones don't matter much, what I wanna get at is explaining to others what we set out to do next. (It should of course still link to the right places for getting actual PM info.)

I'd volunteer to do it for Q1.

**Comment by lgierth** [comment]
This would be ideal for generating discussion on the forum and HN too. It's also an excellent opportunity to get people contributing, of course given we break milestones down into task properly from the start, and attach enough info for it to actually be "ready".

We should probably also explain what we have in mind with regards to making these meetings open and accessible to the community.

**Comment by mishmosh** [comment]
Sounds like there is good support for this. Closing this issue, and replacing it with issues for Q3 & Q4 blog posts specifically.

**Comment by mishmosh** [comment]
See #108
