### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by lgierth** [ipfs/blog#9]
We can deploy it to ipfs.io/blog without touching the website, similar to how github.com/ipfs/refs / ipfs.io/refs is deployed

**Comment by jbenet** [comment]
@lgierth ah yeah, we could. would be nice. also, we could use `blog.ipfs.io` -- if so, we should have both and redirect one to the other.

**Comment by lgierth** [comment]
#11

**Comment by harlantwood** [comment]
@lgierth it seems what when this is working (blog published over ipns and resolving to some path and/or subdomain), we should be able to use exactly the same setup for  publishing the "project repos" board: https://github.com/ipfs/ci-status/issues/9

How manual vs automatic is this  process?  If manual, perhaps I could help with the automation, and we could use a single system to publish these two things when a certain branch of their github repos are updated, from a secure server that we/you control, eg on digital ocean.

I'm thinking of a server that receives github hooks to trigger deploys, described briefly here: https://github.com/ipfs/website/issues/17#issuecomment-156660645

**Comment by harlantwood** [comment]
Continued the thread I started above on https://github.com/ipfs/infrastructure/issues/137.
