### ISSUE TITLE
Q1 2017 Blog Post

### ISSUE THREAD

**Issue by em-ly** [ipfs/blog#90]
@flyingzumwalt mentioned putting together a blog post (https://github.com/ipfs/pm/issues/365#issuecomment-272755766) and I think that's a great idea - wanted to get the ball rolling here. 

> In blog post, if we write it, we should discuss
> 
> stale endeavors
> lessons learned about kanban (loosely coordinated vs. not coordinated)
> thrashing
> sprints, sprintinos

@flyingzumwalt would you like to author this and flesh this out? I feel like you would be the best person to put this piece together.

**Comment by flyingzumwalt** [comment]
I doubt that I'll have time for it during the next 2 weeks. data.gov gets priority.

**Comment by em-ly** [comment]
Understandable - is anyone willing to pick this up?

**Comment by flyingzumwalt** [comment]
I might still be the right one to write it, but that would mean putting out the post in early February. Alternative: put out a basic post now, explaining the changes and pointing to the roadmap, and I can write a more complete explanation in February.

**Comment by em-ly** [comment]
I agree - With the changes to the sprint formats, I think it's important to get a brief post out earlier, mostly introducing the new structure of the sprints. This can also include pointing to the roadmap and the first all hands covering the changes. 

Having a more expanded post in the future is a good idea, especially once the dust settles and we're more in-tune to any areas of clarifications that are needed about the process. It will give time for people to engage and respond to the new process. It might also be a good idea to open up a discourse conversation about the new sprint format, to start fostering feedback and directing questions.

Do you think you would be able to put together a brief post this week?

**Comment by flyingzumwalt** [comment]
I'm maxed out this week. I think someone else could write the first brief, informative post with links to the roadmap and the all-hands video. @RichardLitt would you be able to put that basic post together?

**Comment by RichardLitt** [comment]
@flyingzumwalt I've stubbed out one, here. We should merge the Stale Endeavors PR in ipfs/ipfs, first, and we should also have a way of showing the roadmap in ipfs/pm. Can you take a look and tell me if you want me to severely edit the blogpost before a final polish? 

https://github.com/ipfs/blog/blob/feat/q1-blogpost/src/23-2017-q1-update/index.md

**Comment by em-ly** [comment]
@flyingzumwalt Can you please review the above?

**Comment by flyingzumwalt** [comment]
Reviewed and updated.

**Comment by RichardLitt** [comment]
Lgtm!

**Comment by mishmosh** [comment]
Closing b/c team decided not to publish at the time, and window of opportunity has passed.
