### ISSUE TITLE
Uncensorable Wikipedia post has copyright symbol that may be typo

### ISSUE THREAD

**Issue by arcalinea** [ipfs/blog#96]
https://ipfs.io/blog/24-uncensorable-wikipedia/
At bottom:
"These are read-only snapshots. Supporting full read-and-write would take further work.©"

Also, would be nice to explain or link to IPNS to clarify for new readers unfamiliar with IPFS.

**Comment by flyingzumwalt** [comment]
Yeah. I wanted to link to an explanation of IPNS and found that the only explanation is in the IPFS whitepaper! The docs have examples of how to use ipns but don't explain what it is.

Thanks for catching the typo https://github.com/ipfs/blog/commit/fae5510a339230d9b19a5d550329e4a6bef6fd1a
