### ISSUE TITLE
Blog Post: Base58 issue for browser compatibility

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/blog#99]
We should write a Blog Post about all the things we hashed out with @gozala and @lidel in January around IPFS paths and the single-origin policy

* describe the goals of ipfs in web browsers
* describe the problem of making IPFS addresses compatible with single origin policy (origins are case-insensitive)
* explain how CIDs in IPFS solve this problem
* show working code that uses it

**Comment by lgierth** [comment]
:+1:

(This reminds me that it's actually not yet completely 100% solved, as described in https://github.com/ipfs/specs/pull/152#issuecomment-303092071)
